### ISSUE TITLE
What is your config for Lingon? The scripts works but not on Lingon.

### ISSUE THREAD

**Issue by ntassani** [jonbeebe/MacDynamicWallpaper#2]
I attach my config on Lingon. Its necessary have Lingon opened in the dock all the time?
Thanks for your help!

![2](https://user-images.githubusercontent.com/11095490/41180908-3ade9ad8-6b46-11e8-8255-a3460a4d60d6.jpg)
![1](https://user-images.githubusercontent.com/11095490/41180909-3b1777fe-6b46-11e8-9b7d-492849c357fd.jpg)

**Comment by jonbeebe** [comment]
Hi @ntassani, In my config, I don't have 'Launch again if it crashes' checked, but I don't think that matters. In the advanced tab, I have nothing selected. I also found that a 20 minute interval works best for me. Other than that your config looks good.

With Lingon, you can close the app out completely and it still works, because it is just a GUI wrapper around the built-in OS launch daemons and agents.

**Comment by ntassani** [comment]
Thanks for your help! Is really appreciated. And thanks for share your work.
Regards,
Nicolai.
